(library
 (name ppx_deriving_yaml)
 (public_name ppx_deriving_yaml)
 (modules ppx_deriving_yaml)
 (kind ppx_deriver)
 (libraries ppxlib ppx_deriving_yaml.common yaml)
 (ppx_runtime_libraries ppx_deriving_yaml.runtime yaml)
 (preprocess
  (pps ppxlib.metaquot)))

(library
 (name ppx_deriving_yaml_runtime)
 (public_name ppx_deriving_yaml.runtime)
 (modules ppx_deriving_yaml_runtime)
 (libraries ppx_deriving_yaml.types yaml))

;(mdx
; (files index.mld)
; (package ppx_deriving_yaml)
; (deps
;  (package ppx_deriving_yaml))
; (preludes prelude.ml)
; (libraries ppxlib ppx_deriving_yaml ppx_deriving_yaml.runtime yaml))

(documentation
 (package ppx_deriving_yaml))
