name: Tests for ppx_deriving_yaml
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [macos-latest, ubuntu-latest, windows-latest]
        ocaml-version: [4.11.0, 4.10.0, 4.09.1]
    runs-on: ${{ matrix.operating-system }}
    steps:
    - uses: actions/checkout@v2
    - uses: avsm/setup-ocaml@v1.1.2
      with:
        ocaml-version: ${{ matrix.ocaml-version }}
    - name: Pinning Package
      run: opam pin add -n -y .
    - name: Packages
      run: opam depext -yt ppx_deriving_yaml
    - name: Dependencies
      run: opam install -t -y . --deps-only
    - name: Opam install and test
      run: opam install --with-test .
